language: node_js
node_js: "stable"
install:
  - npm install
service:
  - postgres
before_install:
  - postgres -u postgres --password='' < tests/travis.sql
script:
  - npm test
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
branches: 
  only:
    - feature
after_success:
  - npm run coverage