const MODAL_CONTENT = 'MODAL_CONTENT';
const SIGNIN_FORM = 'SIGNIN_FROM';
const SIGNUP_FORM = 'SIGNUP_FROM';
const PASSWORD_RESET_FORM = "PASSWORD_RESET_FORM";
const PASSWORD_RECOVERY_FORM = "PASSWORD_RECOVERY_FORM";
const ADD_FILE_INPUT = "ADD_FILE_INPUT";
const REMOVE_FILE_INPUT = "REMOVE_FILE_INPUT";
const SHOW_REMOVE_BUTTON = "SHOW_REMOVE_BUTTON";
const SIGNUP_SUCCESSFUL = "SIGNUP_SUCCESSFUL";
const SIGNUP_UNSUCCESSFUL = "SIGNUP_UNSUCCESSFUL";
const SIGNIN_SUCCESSFUL = "SIGNIN_SUCCESSFUL";
const SIGNIN_UNSUCCESSFUL = "SIGNIN_UNSUCCESSFUL";
const HIDE_ALERT_MESSAGE  = "HIDE_ALERT_MESSAGE"
const SHOW_ALERT_MESSAGE  = "SHOW_ALERT_MESSAGE"
const USER_FORM = "USER_FORM";
const ORDER_FORM = "ORDER_FORM";
const SET_CURRENT_USER = "SET_CURRENT_USER";
const SIGNOUT_USER = "SIGNOUT_USER";
const EMAIL_VERIFICATION_ERROR = "EMAIL_VERIFICATION_ERROR";
const USERNAME_VERIFICATION_ERROR = "USERNAME_VERIFICATION_ERROR";
const ORDER_SUCCESSFUL = "ORDER_SUCCESSFUL";
const ORDER_UNSUCCESSFUL = "ORDER_UNSUCCESSFUL";
const REMOVE_ALL_FILE_INPUT = "REMOVE_ALL_FILE_INPUT";

export default {
    MODAL_CONTENT,
    SIGNUP_FORM,
    SIGNIN_FORM,
    USER_FORM,
    ORDER_FORM,
    ORDER_SUCCESSFUL,
    SIGNOUT_USER,
    SIGNUP_SUCCESSFUL,
    SET_CURRENT_USER,
    SIGNUP_UNSUCCESSFUL,
    HIDE_ALERT_MESSAGE,
    SHOW_ALERT_MESSAGE,
    SIGNIN_SUCCESSFUL,
    SIGNIN_UNSUCCESSFUL, 
    REMOVE_FILE_INPUT,
    PASSWORD_RESET_FORM,
    PASSWORD_RECOVERY_FORM,
    ADD_FILE_INPUT,
    SHOW_REMOVE_BUTTON,
    EMAIL_VERIFICATION_ERROR,
    USERNAME_VERIFICATION_ERROR,
    REMOVE_ALL_FILE_INPUT,
}